### ISSUE TITLE
Missing classes

### ISSUE THREAD

**Issue by uniquelau** [rsoeteman/umbraco-admin-reset#7]
Seems like a few files have become missing, as there is no longer a Controllers/TypeExtensions folder.

![image](https://user-images.githubusercontent.com/914735/48013687-c2e63200-e11c-11e8-99ff-ac768763ac0e.png)

**Comment by rsoeteman** [comment]
Hi Laurence,

Sorry thought VS added them automatically. Should be ok now. Thanks for reporting

**Comment by uniquelau** [comment]
Resolved 👍
